--- #YAML:1.0
name: Pipe
version: 0.01
author:
  - Gabor Szabo <gabor@pti.co.il>
abstract: Framework to create pipes using iterators
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
