---
abstract: 'Framework for creating pipes using iterators'
author:
  - 'Gabor Szabo <gabor@szabgab.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pipe
no_index:
  directory:
    - t
    - inc
requires:
  File::Find::Rule: 0.33
  File::Temp: 0
  Test::More: 0.98
  Test::NoWarnings: 1.04
  Want: 0.21
resources:
  repository: https://github.com/szabgab/Pipe
version: 0.04
